upstream clientes {
    server api-clientes:8000;
}

upstream produtos {
    server api-produtos:8000;
}

upstream pedidos {
    server api-pedidos:8000;
}

server {
    listen 80;

    location /clientes {
        proxy_pass http://clientes;
    }

    location /produtos {
        proxy_pass http://produtos;
    }

    location /pedidos {
        proxy_pass http://pedidos;
    }

    location /resumo {
        proxy_pass http://pedidos/resumo-oficina;
    }
}