
services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: oficina_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    volumes:
      - pg_data:/var/lib/postgresql/data 
    networks:
      - oficina-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d oficina_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    volumes:
      - mongo_data:/data/db 
    networks:
      - oficina-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-clientes:
    build: ./api-clientes
    container_name: api-clientes
    ports:
      - "8001:8000" 
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - oficina-net

  api-produtos:
    build: ./api-produtos
    container_name: api-produtos
    ports:
      - "8002:8000"
    depends_on:
      mongo-db:
        condition: service_healthy
    networks:
      - oficina-net

  api-pedidos:
    build: ./api-pedidos
    container_name: api-pedidos
    ports:
      - "8003:8000"
    depends_on:
      api-clientes:
        condition: service_started
      api-produtos:
        condition: service_started
    networks:
      - oficina-net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8081:80"  
    depends_on:
      api-pedidos:
        condition: service_started
    networks:
      - oficina-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:80"
    depends_on:
      - api-clientes
      - api-produtos
      - api-pedidos
    networks:
      - oficina-net

networks:
  oficina-net: 
    driver: bridge

volumes:
  pg_data: 
  mongo_data: